server:
  port: 8080

spring:
  thymeleaf:
    cache: false

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: hotel_registration_cl
            client-secret: M8AbSK8gkYGrTKsKKc4n2JUlTENnjLXV
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:18080/realms/hotel-realm
