server:
  port: 8080

application:
  new-user-roles:
    users:  hotel_data_reader, hotel_provider
    admins: hotel_data_writer, hotel_provider_admin
  client:
    realm: hotel-realm-2
    id: hotel-provider
    url: http://localhost:18080
    secret: V2qlyKNBHZKWG7oMWtR7hNgKPtUCKH90

spring:
  thymeleaf:
    cache: false

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${application.client.id}
            authorization-grant-type: authorization_code
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: ${application.client.url}/realms/${application.client.realm}

logging:
  level:
    org:
      springframework:
        security: DEBUG